# Generated by Django 4.1.7 on 2023-04-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
